# Generated by Django 4.1.7 on 2023-03-27 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_last_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_donated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
