# Generated by Django 4.1.7 on 2023-03-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_donated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_donated',
        ),
    ]
