# Generated by Django 4.2 on 2023-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_last_donated_alter_donations_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_donations',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
