# Generated by Django 4.2 on 2023-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_donations',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
